import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
const labels:Record<string,string>={offer_viewed:'شاهد العروض',offer_selected:'اختار عرضًا',checkout_started:'بدأ الفورم',checkout_error:'واجه خطأ',complement_clicked:'اختار منتجًا مكملًا'};
export default function ConversionDashboard(){
 const [from,setFrom]=useState(new Date(Date.now()-30*86400000).toISOString().slice(0,10));const [to,setTo]=useState(new Date().toISOString().slice(0,10));const [source,setSource]=useState('');const [device,setDevice]=useState('');const [productId,setProductId]=useState('');const [returning,setReturning]=useState('');const [experiment,setExperiment]=useState('');
 const params=new URLSearchParams({from,to,source,device,productId,returning,experiment});
 const {data,error,isFetching}=useQuery<any>({queryKey:['/api/admin/analytics/funnel',params.toString()],queryFn:async()=>{const r=await apiRequest('GET',`/api/admin/analytics/funnel?${params}`);return(await r.json()).data},staleTime:30000});
 const t=data?.totals;const rate=(n:number,d:number)=>d?`${(100*n/d).toFixed(1)}٪`:'—';
 return <section className="rounded-2xl border bg-card p-5 space-y-4" dir="rtl"><h2 className="text-xl font-bold">تحويل فهد · هدف ١٠٪</h2><p className="text-sm text-muted-foreground">أول رسالة أو ضغط عرض/طلب يبدأ التفاعل. التحويل: محادثة نتج عنها طلب صالح خلال ٧ أيام، مرة واحدة مهما تكررت الطلبات. الاختبارات والملغي والمرتجع مستبعدة من التحويل.</p>
 <div className="flex flex-wrap gap-2 text-sm"><label>من<input aria-label="من تاريخ" className="border rounded p-2 block" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>إلى<input aria-label="إلى تاريخ" className="border rounded p-2 block" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>المصدر<input className="border rounded p-2 block" placeholder="كل المصادر" value={source} onChange={e=>setSource(e.target.value)}/></label><label>المنتج<input className="border rounded p-2 block w-24" type="number" placeholder="الكل" value={productId} onChange={e=>setProductId(e.target.value)}/></label><select aria-label="الجهاز" className="border rounded p-2" value={device} onChange={e=>setDevice(e.target.value)}><option value="">كل الأجهزة</option><option value="mobile">موبايل</option><option value="desktop">كمبيوتر</option></select><select aria-label="نوع العميل" className="border rounded p-2" value={returning} onChange={e=>setReturning(e.target.value)}><option value="">كل العملاء</option><option value="false">جديد</option><option value="true">عائد</option></select><select aria-label="التجربة" className="border rounded p-2" value={experiment} onChange={e=>setExperiment(e.target.value)}><option value="">كل النسخ</option><option value="baseline">خط الأساس</option><option value="offer-value-v1:control">العروض · الأصلية</option><option value="offer-value-v1:variant">العروض · أفضل سعر</option></select></div>
 {error&&<p role="alert">تعذر تحميل القياس</p>}{isFetching&&<p role="status" className="text-xs">جار التحديث…</p>}
 {t&&<><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[['المحادثات المتفاعلة',t.engaged],['التحويل الأولي',rate(t.converted,t.engaged)],['تحويل بعد اكتمال ٧ أيام',rate(t.matureConverted,t.mature)],['المحادثات المكتملة المدة',t.mature],['وصلت للتأكيد',rate(t.confirmed,t.engaged)],['تم التسليم',rate(t.delivered,t.engaged)],['فيها إلغاء',rate(t.cancelled,t.engaged)],['فيها مرتجع',rate(t.returned,t.engaged)]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-muted p-3"><p className="text-xs">{label}</p><b className="text-xl">{value}</b></div>)}</div><p className="text-xs text-muted-foreground">الأرقام الأولية قد تتغير حتى اكتمال نافذة الإسناد. تجاوز ١٠٪ في عينة صغيرة لا يثبت تحسنًا مستمرًا.</p><div className="flex flex-wrap gap-3">{data.stages.map((s:any)=><span className="border rounded-xl p-3 text-sm" key={s.event}>{labels[s.event]}: <b>{s.count}</b></span>)}</div><details><summary>تفصيل المنتجات والمصادر</summary><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>المصدر</th><th>الجهاز</th><th>المنتج</th><th>التفاعل</th><th>التحويل</th></tr></thead><tbody>{data.segments.map((s:any,i:number)=><tr key={i}><td>{s.source}</td><td>{s.device}</td><td>{s.productId||'عام'}</td><td>{s.engaged}</td><td>{rate(s.converted,s.engaged)}</td></tr>)}</tbody></table></div></details></>}
 </section>
}
