import ts from 'typescript';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const code = ts.transpileModule(fs.readFileSync('src/lib/tiktok.ts','utf8'), {compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const scripts=[]; const storage=new Map();
globalThis.window={}; globalThis.document={createElement:()=>({}),head:{appendChild:script=>scripts.push(script)}};
globalThis.localStorage={getItem:key=>storage.get(key),setItem:(key,value)=>storage.set(key,value)};
let enabled=false;
globalThis.fetch=async()=>({ok:true,json:async()=>({data:{enabled,pixelId:'TESTPIXEL1234567890'}})});
const {trackTikTokPurchase}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const receipt={id:1,orderNumber:'TEST-1',totals:{grandTotal:178,currency:'SAR'},items:[{productId:3,qty:2,unitPrice:89}]};
await trackTikTokPurchase(receipt); assert.equal(scripts.length,0);
enabled=true;
await Promise.all([trackTikTokPurchase(receipt),trackTikTokPurchase(receipt)]);
await trackTikTokPurchase(receipt);
assert.equal(scripts.length,1);
const events=window.ttq._i.TESTPIXEL1234567890;
assert.equal(events.length,1);assert.equal(events[0][0],'track');assert.equal(events[0][1],'Purchase');
assert.equal(events[0][2].value,178);assert.equal(events[0][2].contents[0].quantity,2);assert.equal(events[0][3].event_id,'purchase_TEST-1');
assert.equal(events[0][2].customer,undefined);
await trackTikTokPurchase({...receipt,id:2,orderNumber:'TEST-2'});assert.equal(events.length,2);
globalThis.fetch=async()=>{throw new Error('offline')};
await trackTikTokPurchase({...receipt,id:3,orderNumber:'TEST-3'});assert.equal(events.length,2);
console.log('PASS: disabled pixel, successful receipt, duplicate/concurrent callbacks, distinct orders, payload, network failure');
