import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

type City={id:number;name:string;shippingFee:number;deliveryEstimate:string;isActive:boolean};
export default function CitiesPage(){const qc=useQueryClient();const [draft,setDraft]=useState({name:"",shippingFee:"",deliveryEstimate:""});const [editing,setEditing]=useState<number|null>(null);const {data:cities=[],isLoading}=useQuery<City[]>({queryKey:['/api/cities'],queryFn:async()=>{const r=await apiRequest('GET','/api/admin/cities');return (await r.json()).data||[]}});const save=useMutation({mutationFn:async(city:Partial<City>)=>apiRequest(editing?'PATCH':'POST',editing?`/api/admin/cities/${editing}`:'/api/admin/cities',city),onSuccess:()=>{qc.invalidateQueries({queryKey:['/api/cities']});setDraft({name:"",shippingFee:"",deliveryEstimate:""});setEditing(null)}});const edit=(c:City)=>{setEditing(c.id);setDraft({name:c.name,shippingFee:String(c.shippingFee||0),deliveryEstimate:c.deliveryEstimate||''})};const toggle=(c:City)=>save.mutate({isActive:!c.isActive});return <div dir="rtl" className="p-6 space-y-5 max-w-5xl mx-auto"><div><h1 className="text-2xl font-bold">المدن والتوصيل</h1><p className="text-sm text-muted-foreground">إدارة المدن الظاهرة في نموذج الطلب ورسوم ووقت التوصيل.</p></div><form className="grid md:grid-cols-4 gap-2 rounded-xl border bg-card p-4" onSubmit={e=>{e.preventDefault();if(draft.name.trim())save.mutate({name:draft.name,shippingFee:Number(draft.shippingFee||0),deliveryEstimate:draft.deliveryEstimate,isActive:true})}}><Input required placeholder="اسم المدينة" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><Input type="number" min="0" placeholder="رسوم الشحن" value={draft.shippingFee} onChange={e=>setDraft({...draft,shippingFee:e.target.value})}/><Input placeholder="مدة التوصيل" value={draft.deliveryEstimate} onChange={e=>setDraft({...draft,deliveryEstimate:e.target.value})}/><Button disabled={save.isPending}>{editing?'حفظ التعديل':'إضافة مدينة'}</Button></form><div className="rounded-xl border overflow-hidden"><div className="grid grid-cols-[1fr_120px_150px_100px] gap-2 p-3 bg-muted font-semibold text-sm"><span>المدينة</span><span>الشحن</span><span>المدة</span><span>الحالة</span></div>{isLoading?<p className="p-4">جاري التحميل…</p>:cities.map(city=><div key={city.id} className="grid grid-cols-[1fr_120px_150px_100px] gap-2 items-center p-3 border-t text-sm"><span>{city.name}</span><span>{city.shippingFee||0} ر.س</span><span>{city.deliveryEstimate||'غير محدد'}</span><span className="flex items-center gap-2"><Switch checked={city.isActive} onCheckedChange={()=>toggle(city)}/><Button variant="ghost" size="sm" onClick={()=>edit(city)}>تعديل</Button></span></div>)}</div></div>}
